"""
bark_tts.py — A better CLI for Bark TTS (github.com/suno-ai/bark)

QUICK START:
  python bark_tts.py "Hello world"
  python bark_tts.py "Hello world" --voice v2/en_speaker_9 --play
  python bark_tts.py --interactive
  python bark_tts.py --list-voices
  python bark_tts.py --clone "recording.wav" --clone-out voices/me.npz

FULL USAGE:
  python bark_tts.py <text>           [--voice PRESET] [--out FILE]
                                      [--play] [--temp T] [--seed N]
                                      [--small] [--cpu]
  python bark_tts.py --interactive    [--voice PRESET] [--temp T]
  python bark_tts.py --list-voices
  python bark_tts.py --clone WAV      [--clone-out FILE]

OFFICIAL BARK NON-VERBAL TOKENS:
  [laughter]  [laughs]  [sighs]  [gasps]  [clears throat]  [music]  ♪
  Use ... or — for hesitations.  CAPS for emphasis.
  Example: "That is AMAZING. [laughs] ... okay, let me think."

VOICE PRESETS (built-in):
  Female: v2/en_speaker_0  v2/en_speaker_3  v2/en_speaker_9
  Male:   v2/en_speaker_1  v2/en_speaker_6  v2/en_speaker_7
  --voice also accepts a path to a .npz cloned voice file

VOICE CLONING:
  --clone encodes a WAV into a .npz speaker profile (HuBERT + EnCodec).
  This is a one-time step — the resulting .npz is reused with --voice at no
  extra inference cost. Uses HuBERT for semantic tokens + EnCodec for acoustic.
  Example:
    python bark_tts.py --clone "vivian.wav" --clone-out voices/vivian.npz
    python bark_tts.py "Hello!" --voice voices/vivian.npz --play

ROLLING CONTEXT (automatic for long texts):
  When text is split into multiple chunks, each chunk is conditioned on the
  tokens generated by the previous chunk instead of the static voice profile.
  This keeps voice, prosody, and pacing consistent across sentence boundaries.

TEMPERATURE:
  --temp controls both text and waveform generation (default: 0.7)
  Lower (0.3–0.5) = more predictable, less filler "um"s
  Higher (0.8–1.0) = more expressive/varied, less stable

ENV VARS:
  SUNO_USE_SMALL_MODELS=1   use smaller/faster models (~1GB instead of ~5GB)
  SUNO_OFFLOAD_CPU=1        offload unused models to CPU (saves VRAM)
"""

import argparse
import os
import sys
import time

import numpy as np
import scipy.io.wavfile as wav

# ── Optional playback ────────────────────────────────────────────────────────
try:
    import sounddevice as sd
    _HAS_SOUNDDEVICE = True
except ImportError:
    _HAS_SOUNDDEVICE = False

# ── Bark lives in the bark/ subdirectory (cloned repo) ───────────────────────
_HERE = os.path.dirname(os.path.abspath(__file__))
_BARK_DIR = os.path.join(_HERE, "bark")
if _BARK_DIR not in sys.path:
    sys.path.insert(0, _BARK_DIR)

# ── bark-with-voice-clone (HuBERT voice cloning support) ─────────────────────
# NOTE: appended, not inserted — bark-with-voice-clone also contains a bark/
# subfolder; keeping _BARK_DIR first ensures the correct generation.py is used.
_BWVC_DIR = os.path.join(_HERE, "bark-with-voice-clone")
if os.path.isdir(_BWVC_DIR) and _BWVC_DIR not in sys.path:
    sys.path.append(_BWVC_DIR)

# Lazy-loaded so --list-voices / --help work without loading models
_models_loaded = False


def _load_models(small: bool = False, cpu: bool = False) -> None:
    global _models_loaded
    if _models_loaded:
        return
    if small:
        os.environ["SUNO_USE_SMALL_MODELS"] = "1"
    if cpu:
        os.environ["SUNO_OFFLOAD_CPU"] = "1"
    from bark.generation import preload_models
    print("Loading Bark models (first run downloads ~5 GB to ~/.cache/suno/)…")
    preload_models()
    _models_loaded = True


def _split_sentences(text: str) -> list[str]:
    """Split text into sentence-sized chunks (~13s max per Bark context window)."""
    import re
    # Split on sentence-ending punctuation, keeping the delimiter
    parts = re.split(r'(?<=[.!?…])\s+', text.strip())
    chunks = []
    current = ""
    for part in parts:
        candidate = (current + " " + part).strip() if current else part
        # Rough proxy: Bark encodes ~13 chars/token for English; 200 chars ≈ safe limit
        if len(candidate) > 200 and current:
            chunks.append(current)
            current = part
        else:
            current = candidate
    if current:
        chunks.append(current)
    return chunks or [text]


def _validate_voice(voice: str | None) -> None:
    """Raise a clear error early if an unsupported voice format is given."""
    if voice is None:
        return
    ext = os.path.splitext(voice)[1].lower()
    audio_exts = {".wav", ".mp3", ".flac", ".ogg", ".m4a", ".aac"}
    if ext in audio_exts:
        sys.exit(
            f"\n[ERROR] Bark cannot use a {ext!r} file as a voice reference directly.\n"
            "\n"
            "Bark requires a .npz speaker profile, not a raw audio file.\n"
            "Create one from your recording with:\n"
            "\n"
            f"  python bark_tts.py --clone \"{voice}\" --clone-out voices/my_voice.npz\n"
            "\n"
            "Then generate with it:\n"
            "  python bark_tts.py \"your text\" --voice voices/my_voice.npz --play\n"
        )


def _generate(
    text: str,
    voice: str | None,
    temp: float,
    seed: int | None,
    small: bool,
    cpu: bool,
) -> tuple[np.ndarray, int]:
    """Run generation and return (audio_array, sample_rate).

    Long texts are automatically split into sentence chunks. Each chunk is
    conditioned on the tokens generated by the *previous* chunk (rolling
    context) rather than the static voice profile, keeping voice and prosody
    consistent across sentence boundaries.
    """
    import torch
    from bark.generation import (
        generate_text_semantic,
        generate_coarse,
        generate_fine,
        codec_decode,
        SAMPLE_RATE,
    )

    _validate_voice(voice)
    _load_models(small=small, cpu=cpu)

    if seed is not None:
        torch.manual_seed(seed)
        np.random.seed(seed)

    chunks = _split_sentences(text)
    if len(chunks) > 1:
        print(f"  (splitting into {len(chunks)} chunks — rolling context enabled)")

    audio_parts = []
    history_prompt = voice  # chunk 1: seed from the voice profile

    for i, chunk in enumerate(chunks):
        if len(chunks) > 1:
            print(f"  Chunk {i+1}/{len(chunks)}: \"{chunk[:60]}{'…' if len(chunk)>60 else ''}\"")

        semantic = generate_text_semantic(
            chunk,
            history_prompt=history_prompt,
            temp=temp,
            min_eos_p=0.05,
        )
        coarse = generate_coarse(
            semantic,
            history_prompt=history_prompt,
            temp=temp,
        )
        fine = generate_fine(
            coarse,
            history_prompt=history_prompt,
            temp=0.5,
        )
        audio_parts.append(codec_decode(fine))

        # Pass the end of this chunk as context into the next one
        history_prompt = {
            "semantic_prompt": semantic,
            "coarse_prompt":   coarse,
            "fine_prompt":     fine,
        }

    audio = np.concatenate(audio_parts) if len(audio_parts) > 1 else audio_parts[0]
    return audio, SAMPLE_RATE


def _play(audio: np.ndarray, sr: int) -> None:
    if not _HAS_SOUNDDEVICE:
        print("sounddevice not installed — run: pip install sounddevice", file=sys.stderr)
        return
    sd.play(audio.astype(np.float32), samplerate=sr)
    sd.wait()


def _save(audio: np.ndarray, sr: int, path: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    pcm = (np.clip(audio, -1.0, 1.0) * 32767).astype(np.int16)
    wav.write(path, sr, pcm)
    print(f"Saved → {path}  ({len(pcm)/sr:.2f}s)")


# HuBERT tokenizer checkpoint — downloaded once to voices/.hubert_cache/
_HUBERT_TOKENIZER_REPO  = "GitMylo/bark-voice-cloning"
_HUBERT_TOKENIZER_FILE  = "quantifier_hubert_base_ls960_14.pth"
_HUBERT_CACHE_DIR       = os.path.join(_HERE, "voices", ".hubert_cache")
_HUBERT_TOKENIZER_PATH  = os.path.join(_HUBERT_CACHE_DIR, "tokenizer.pth")


def _ensure_hubert_tokenizer() -> str:
    """Download the HuBERT discrete tokenizer checkpoint on first use."""
    if os.path.isfile(_HUBERT_TOKENIZER_PATH):
        return _HUBERT_TOKENIZER_PATH
    import shutil
    from huggingface_hub import hf_hub_download
    os.makedirs(_HUBERT_CACHE_DIR, exist_ok=True)
    print("[+] Downloading HuBERT tokenizer (~24 MB, one-time)...")
    tmp = hf_hub_download(
        repo_id=_HUBERT_TOKENIZER_REPO,
        filename=_HUBERT_TOKENIZER_FILE,
        local_dir=_HUBERT_CACHE_DIR,
    )
    if os.path.abspath(tmp) != os.path.abspath(_HUBERT_TOKENIZER_PATH):
        shutil.move(tmp, _HUBERT_TOKENIZER_PATH)
    print(f"    Cached → {_HUBERT_TOKENIZER_PATH}")
    return _HUBERT_TOKENIZER_PATH


def cmd_clone(args: argparse.Namespace) -> None:
    """Encode a WAV file into a .npz speaker profile using HuBERT + EnCodec.

    Uses transformers.HubertModel (already installed as a Bark dependency) for
    semantic token extraction — no extra packages needed.
    One-time step — the resulting .npz is passed to --voice for all future
    generations with no additional inference cost.
    """
    import torch
    import torchaudio
    import torchaudio.transforms as T
    from transformers import HubertModel
    from bark.generation import load_codec_model
    from encodec.utils import convert_audio

    audio_path = args.clone
    if not os.path.isfile(audio_path):
        sys.exit(f"[ERROR] Audio file not found: {audio_path}")

    out_path = args.clone_out
    if out_path is None:
        stem = os.path.splitext(os.path.basename(audio_path))[0]
        out_path = os.path.join("voices", f"{stem}.npz")

    # CustomTokenizer lives in bark-with-voice-clone/hubert/ — only needed for
    # the tokenizer checkpoint loader (pure PyTorch, no fairseq).
    if not os.path.isdir(_BWVC_DIR):
        sys.exit(
            "[ERROR] bark-with-voice-clone/ not found in BarkTTS folder.\n"
            "Run setup.ps1 to clone it, or manually:\n"
            "  git clone https://github.com/serp-ai/bark-with-voice-clone bark-with-voice-clone"
        )
    from hubert.customtokenizer import CustomTokenizer

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[+] Cloning voice from: {audio_path}")
    print(f"    Output: {out_path}")
    print(f"    Device: {device}")
    t0 = time.time()

    # ── EnCodec (Bark's built-in codec) ──────────────────────────────────────
    print("[+] Loading EnCodec model...")
    codec = load_codec_model(use_gpu=(device == "cuda"))

    # ── HuBERT feature extractor (facebook/hubert-base-ls960 via transformers)
    # Downloads ~360 MB on first use, cached by HuggingFace in ~/.cache/huggingface/
    print("[+] Loading HuBERT model (downloads ~360 MB on first run, then cached)...")
    hubert = HubertModel.from_pretrained("facebook/hubert-base-ls960").to(device)
    hubert.eval()

    # ── HuBERT tokenizer checkpoint (~24 MB, cached in voices/.hubert_cache/) ─
    tokenizer_ckpt = _ensure_hubert_tokenizer()
    print("[+] Loading HuBERT tokenizer...")
    tokenizer = CustomTokenizer.load_from_checkpoint(tokenizer_ckpt).to(device)

    # ── Load + normalise audio ────────────────────────────────────────────────
    print("[+] Processing audio...")
    audio_wav, sr = torchaudio.load(audio_path)

    dur = audio_wav.shape[-1] / sr
    print(f"    Duration: {dur:.1f}s  (ideal: 10–30s, minimum ~5s)")
    if dur < 5:
        print("    WARNING: very short reference (<5s) — clone quality may be poor.")

    # EnCodec path: resample to 24 kHz mono
    audio_encodec = convert_audio(audio_wav, sr, codec.sample_rate, codec.channels).to(device)

    # HuBERT path: resample to 16 kHz mono (HuBERT's native rate)
    audio_hubert = T.Resample(sr, 16000)(audio_wav).mean(dim=0, keepdim=True).to(device)

    # ── HuBERT → semantic tokens ──────────────────────────────────────────────
    # Extract layer-9 hidden states (same layer CustomHubert used with fairseq)
    print("[+] Extracting semantic tokens (HuBERT layer 9)...")
    with torch.no_grad():
        outputs = hubert(audio_hubert.squeeze(0).unsqueeze(0), output_hidden_states=True)
    hidden = outputs.hidden_states[9]          # [1, T, 768]
    semantic_vectors = hidden.squeeze(0)       # [T, 768]
    semantic_tokens = tokenizer.get_token(semantic_vectors)

    # ── EnCodec → coarse + fine codes ────────────────────────────────────────
    print("[+] Extracting audio codes (EnCodec)...")
    with torch.no_grad():
        encoded_frames = codec.encode(audio_encodec.unsqueeze(0))
    codes = torch.cat([frame[0] for frame in encoded_frames], dim=-1).squeeze()  # [n_q, T]

    semantic_tokens = semantic_tokens.cpu().numpy()
    codes = codes.cpu().numpy()

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    np.savez(
        out_path,
        semantic_prompt=semantic_tokens,
        coarse_prompt=codes[:2, :],
        fine_prompt=codes,
    )

    elapsed = time.time() - t0
    print(f"\n[+] Speaker profile saved → {out_path}  ({elapsed:.1f}s)")
    print(f"    Use with:  python bark_tts.py \"your text\" --voice \"{out_path}\" --play")


def cmd_generate(args: argparse.Namespace) -> None:
    text = args.text
    print(f'Generating: "{text}"')
    t0 = time.time()
    audio, sr = _generate(
        text=text,
        voice=args.voice,
        temp=args.temp,
        seed=args.seed,
        small=args.small,
        cpu=args.cpu,
    )
    print(f"Done in {time.time()-t0:.1f}s  ({len(audio)/sr:.2f}s of audio)")

    if args.out:
        _save(audio, sr, args.out)
    else:
        # Default output filename based on first few words
        slug = "_".join(text.split()[:4])
        slug = "".join(c if c.isalnum() or c == "_" else "" for c in slug)[:40]
        path = os.path.join(args.output_dir, f"{slug}.wav")
        _save(audio, sr, path)

    if args.play:
        _play(audio, sr)


def cmd_interactive(args: argparse.Namespace) -> None:
    print("Bark interactive mode  (Ctrl-C or type 'quit' to exit)")
    print(f"Voice: {args.voice or 'default'}  |  Temp: {args.temp}")
    if args.voice:
        print(f"Using voice: {args.voice}")
    print()

    # Pre-load once so the loop is snappy
    _load_models(small=args.small, cpu=args.cpu)

    session_dir = os.path.join(
        args.output_dir, f"session_{int(time.time())}"
    )
    os.makedirs(session_dir, exist_ok=True)
    count = 0

    while True:
        try:
            text = input(">>> ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nExiting.")
            break

        if not text or text.lower() in ("quit", "exit", "q"):
            break

        # Allow changing voice mid-session: /voice v2/en_speaker_3
        if text.startswith("/voice "):
            args.voice = text[7:].strip()
            print(f"Voice → {args.voice}")
            continue
        if text.startswith("/temp "):
            try:
                args.temp = float(text[6:].strip())
                print(f"Temp → {args.temp}")
            except ValueError:
                print("Usage: /temp 0.5")
            continue
        if text in ("/help", "/?"):
            print("  /voice PRESET   — change voice  (e.g. /voice v2/en_speaker_0)")
            print("  /temp VALUE     — change temperature  (e.g. /temp 0.4)")
            print("  /quit           — exit")
            continue

        t0 = time.time()
        try:
            audio, sr = _generate(
                text=text,
                voice=args.voice,
                temp=args.temp,
                seed=args.seed,
                small=args.small,
                cpu=args.cpu,
            )
        except Exception as exc:
            print(f"  Error: {exc}")
            continue

        count += 1
        path = os.path.join(session_dir, f"{count:03d}.wav")
        _save(audio, sr, path)
        print(f"  Generated in {time.time()-t0:.1f}s")

        if args.play:
            _play(audio, sr)


def cmd_list_voices() -> None:
    """Print all built-in voice presets."""
    voices = {
        "English (female)":  ["v2/en_speaker_0", "v2/en_speaker_3", "v2/en_speaker_9"],
        "English (male)":    ["v2/en_speaker_1", "v2/en_speaker_2", "v2/en_speaker_4",
                               "v2/en_speaker_5", "v2/en_speaker_6", "v2/en_speaker_7",
                               "v2/en_speaker_8"],
        "German":   [f"v2/de_speaker_{i}" for i in range(10)],
        "Spanish":  [f"v2/es_speaker_{i}" for i in range(10)],
        "French":   [f"v2/fr_speaker_{i}" for i in range(10)],
        "Hindi":    [f"v2/hi_speaker_{i}" for i in range(10)],
        "Italian":  [f"v2/it_speaker_{i}" for i in range(10)],
        "Japanese": [f"v2/ja_speaker_{i}" for i in range(10)],
        "Korean":   [f"v2/ko_speaker_{i}" for i in range(10)],
        "Polish":   [f"v2/pl_speaker_{i}" for i in range(10)],
        "Portuguese": [f"v2/pt_speaker_{i}" for i in range(10)],
        "Russian":  [f"v2/ru_speaker_{i}" for i in range(10)],
        "Turkish":  [f"v2/tr_speaker_{i}" for i in range(10)],
        "Chinese":  [f"v2/zh_speaker_{i}" for i in range(10)],
    }
    for lang, presets in voices.items():
        print(f"\n{lang}:")
        for p in presets:
            print(f"  {p}")
    print("\nPass any of these to --voice, e.g.:  --voice v2/en_speaker_9")
    print("You can also pass a path to a .npz cloned voice file.")


# ── CLI ───────────────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bark_tts",
        description="Bark TTS — better CLI  (github.com/suno-ai/bark)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # Positional text (optional — omit for --interactive)
    parser.add_argument(
        "text", nargs="?", default=None,
        help="Text to synthesize. Omit to use --interactive mode.",
    )

    # Voice / quality
    parser.add_argument(
        "--voice", "-v", default=None, metavar="PRESET",
        help="Voice preset string or path to .npz cloned voice. "
             "Run --list-voices to see all options. (default: Bark's random voice)",
    )
    parser.add_argument(
        "--temp", "-t", type=float, default=0.7, metavar="T",
        help="Generation temperature for both text and waveform stages. "
             "Lower = less filler/variance. Recommended range: 0.4–0.8. (default: 0.7)",
    )
    parser.add_argument(
        "--seed", type=int, default=None, metavar="N",
        help="Random seed for reproducible output.",
    )

    # Output
    parser.add_argument(
        "--out", "-o", default=None, metavar="FILE",
        help="Output .wav file path. Default: auto-named in --output-dir.",
    )
    parser.add_argument(
        "--output-dir", default="output", metavar="DIR",
        help="Directory for auto-named output files. (default: ./output/)",
    )
    parser.add_argument(
        "--play", "-p", action="store_true",
        help="Play audio immediately after generating.",
    )

    # Modes
    parser.add_argument(
        "--interactive", "-i", action="store_true",
        help="Interactive prompt loop. Type text, get audio. /voice and /temp to change settings.",
    )
    parser.add_argument(
        "--list-voices", action="store_true",
        help="Print all built-in voice presets and exit.",
    )

    # Performance
    parser.add_argument(
        "--small", action="store_true",
        help="Use smaller/faster models (~1 GB vs ~5 GB). Lower quality.",
    )
    parser.add_argument(
        "--cpu", action="store_true",
        help="Offload unused models to CPU to save VRAM (slower).",
    )

    # Voice cloning
    parser.add_argument(
        "--clone", metavar="WAV",
        help="Audio file to encode into a .npz speaker profile using HuBERT + EnCodec. "
             "Run once; reuse the .npz with --voice for all future generation.",
    )
    parser.add_argument(
        "--clone-out", default=None, metavar="FILE",
        help="Output .npz path for --clone. Default: voices/<filename>.npz",
    )

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.list_voices:
        cmd_list_voices()
        return

    if args.clone:
        cmd_clone(args)
        return

    if args.interactive:
        cmd_interactive(args)
        return

    if not args.text:
        parser.print_help()
        print("\nError: provide text to synthesize, or use --interactive.", file=sys.stderr)
        sys.exit(1)

    cmd_generate(args)


if __name__ == "__main__":
    main()
